### ISSUE TITLE
line   19: E117: Unknown function: and E15: Invalid expression: and(g:sh_fold_enabled,1) line   22:

### ISSUE THREAD

**Issue by btihen** [kovetskiy/vim-bash#1]
These errors are happening even on a blank file.

I am using: 
Mac OS X: 10.11.6 (15G31)
vim: stable 7.4.2109 (bottled), HEAD -- From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb
Installed using Vundle

Error detected while processing /Users/btihen/.vim/bundle/vim-bash/syntax/sh.vim:
line   19:
E117: Unknown function: and
E15: Invalid expression: and(g:sh_fold_enabled,1)
line   22:
E117: Unknown function: and
E15: Invalid expression: and(g:sh_fold_enabled,2)
line   25:
E117: Unknown function: and
E15: Invalid expression: and(g:sh_fold_enabled,4)
line   41:
E121: Undefined variable: s:sh_fold_functions
E15: Invalid expression: s:sh_fold_functions
line   46:
E121: Undefined variable: s:sh_fold_heredoc
E15: Invalid expression: s:sh_fold_heredoc
line   51:
E121: Undefined variable: s:sh_fold_ifdofor
E15: Invalid expression: s:sh_fold_ifdofor
line  167:
E492: Not an editor command: ShFoldIfDoFor syn region shDo^Itransparent^Imatchgroup=shConditional start="<do>" matchgr
oup=shConditional end="<done>"^I^I^Icontains=@shLoopList
line  168:
E492: Not an editor command: ShFoldIfDoFor syn region shIf^Itransparent^Imatchgroup=shConditional start="<if_s" matchg
roup=shConditional skip=+-fi>\+ end="<;_s_then>" end="<fi>"^Icontains=@shIfList
line  169:
E492: Not an editor command: ShFoldIfDoFor syn region shFor^I^Imatchgroup=shLoop start="<for\ze_s\s_\%((()\@!" end="\
<in\>" end="<do>"me=e-2^I^I^Icontains=@shLoopList,shDblParen skipwhite nextgroup=shCurlyIn
line  170:
E492: Not an editor command: ShFoldIfDoFor syn region shForPP^Imatchgroup=shLoop start='<for>_s_((' end='))' contains
=shTestOpr
line  185:
E492: Not an editor command: ShFoldIfDoFor syn region  shCase^Icontained skipwhite skipnl matchgroup=shSnglCase start="\
%(\.|[^#$()'" \t]){-}\zs)"  end=";;" end="esac"me=s-1 contains=@shCaseList nextgroup=shCaseStart,shCase,shComment
line  186:
E492: Not an editor command: ShFoldIfDoFor syn region  shCaseEsac^Imatchgroup=shConditional start="<case>" end="<esac
>"^Icontains=@shCaseEsacList
line  266:
E492: Not an editor command:  ShFoldHereDoc syn region shHereDoc matchgroup=shHereDoc07 start="<<\s_\\=\z([^ \t|]+)"^
I^Imatchgroup=shHereDoc07 end="^\z1\s_$"^Icontains=@shDblQuoteList
line  305:
E492: Not an editor command: ShFoldFunctions syn region shFunctionOne^Imatchgroup=shFunction start="^\s_[-a-zA-Z_0-9:]_\
s_()_s_{"^I^Iend="}"^Icontains=@shFunctionList^I^I^Iskipwhite skipnl nextgroup=shFunctionStart,shQuickComment
line  306:
E492: Not an editor command: ShFoldFunctions syn region shFunctionTwo^Imatchgroup=shFunction start="<[^d][^o]&[-a-zA-Z
_0-9:]_\s_\%(())\=_s_{"^Iend="}"^Icontains=shFunctionKey,@shFunctionList contained^Iskipwhite skipnl nextgroup=shFunct
ionStart,shQuickComment
line  307:
E492: Not an editor command: ShFoldFunctions syn region shFunctionThree^Imatchgroup=shFunction start="^\s_[-a-zA-Z_0-9:]
*\s_()_s_("^I^Iend=")"^Icontains=@shFunctionList^I^I^Iskipwhite skipnl nextgroup=shFunctionStart,shQuickComment
line  308:
E492: Not an editor command: ShFoldFunctions syn region shFunctionFour^Imatchgroup=shFunction start="<[^d][^o]&[-a-zA-
Z_0-9:]_\s_\%(())\=_s_)"^Iend=")"^Icontains=shFunctionKey,@shFunctionList contained^Iskipwhite skipnl nextgroup=shFunc
tionStart,shQuickComment
line  418:
E394: Didn't find region item for shDo
E475: Invalid argument: shDoSync^Igrouphere^IshDo^I"<do>"
line  419:
E394: Didn't find region item for shDo
E475: Invalid argument: shDoSync^Igroupthere^IshDo^I"<done>"
line  420:
E394: Didn't find region item for shFor
E475: Invalid argument: shForSync^Igrouphere^IshFor^I"<for>"
line  421:
E394: Didn't find region item for shFor
E475: Invalid argument: shForSync^Igroupthere^IshFor^I"<in>"
line  422:
E394: Didn't find region item for shIf
E475: Invalid argument: shIfSync^Igrouphere^IshIf^I"<if>"
line  423:
E394: Didn't find region item for shIf
E475: Invalid argument: shIfSync^Igroupthere^IshIf^I"<fi>"
line  554:
E184: No such user-defined command: ShFoldFunctions

**Comment by seletskiy** [comment]
@btihen: What does `:echo and(2, 6)` says?

**Comment by btihen** [comment]
E117: Unknown function: and
E15: Invalid expression: and(2, 6)

**Comment by seletskiy** [comment]
@btihen: You vim version for whatever reason lacks builtin `and()` function. What `:h and()` says?

**Comment by btihen** [comment]
FIXED -- thanks.

I discovered I was using the default vim installed by apple -- this has the problem.
I switched to the recent **brew** version of vim -- **now the problem is FIXED**

**vim --version**

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

Then I installed the homebrew version:
**now it works properly again -- thanks.**

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 28 2016 14:11:47)
MacOS X (unix) version
Included patches: 1-2109
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +find_in_path    +mouse_urxvt     -tcl
+autocmd         +float           +mouse_xterm     +termguicolors
-balloon_eval    +folding         +multi_byte      +terminfo
-browse          -footer          +multi_lang      +termresponse
++builtin_terms  +fork()          -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +packages        -toolbar
-clientserver    +insert_expand   +path_extra      +user_commands
+clipboard       +job             +perl            +vertsplit
+cmdline_compl   +jumplist        +persistent_undo +virtualedit
+cmdline_hist    +keymap          +postscript      +visual
+cmdline_info    +langmap         +printer         +visualextra
+comments        +libcall         +profile         +viminfo
+conceal         +linebreak       +python          +vreplace
+cryptv          +lispindent      -python3         +wildignore
+cscope          +listcmds        +quickfix        +wildmenu
+cursorbind      +localmap        +reltime         +windows
+cursorshape     -lua             +rightleft       +writebackup
+dialog_con      +menu            +ruby            -X11
+diff            +mksession       +scrollbind      -xfontset
+digraphs        +modify_fname    +signs           -xim
-dnd             +mouse           +smartindent     -xsmp
-ebcdic          -mouseshape      +startuptime     -xterm_clipboard
+emacs_tags      +mouse_dec       +statusline      -xterm_save
+eval            -mouse_gpm       -sun_workshop    -xpm
+ex_extra        -mouse_jsbterm   +syntax          
+extra_search    +mouse_netterm   +tag_binary      
+farsi           +mouse_sgr       +tag_old_static  
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/Cellar/python/2.7.12/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1/lib    
```
